# Generated by Django 5.0.3 on 2024-07-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100, unique=True)),
                ('current_balance', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('opened_date_time', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
