# Generated by Django 5.0.3 on 2024-07-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_account_remove_transaction_wallet_remove_wallet_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='card_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
