# Generated by Django 5.0.2 on 2024-07-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_account_available_balance_account_blocked_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='PAYMENT', max_length=20),
        ),
    ]
